name: linux-photo-booth
version: '1.0.0'
summary: Professional photo booth application for Ubuntu Core
description: |
  A professional photo booth application designed for Ubuntu Core and Ubuntu Frame.
  Perfect for events, parties, and commercial photo booth installations.
  
  Features:
  - Real-time camera capture using GStreamer
  - Multiple photo layouts (1x1, 2x2)
  - Frame overlay system with customizable templates
  - Direct printing via CUPS
  - Countdown timer with visual feedback
  - Touch-optimized interface
  - Automatic kiosk mode with Ubuntu Frame
  - Background themes and customization
  - Remote management capabilities

grade: stable
confinement: strict
base: core24

platforms:
  amd64:
  arm64:

apps:
  linux-photo-booth:
    command: bin/run-booth
    extensions: [gnome]
    plugs:
      - camera
      - cups-control
      - network
      - network-bind
      - home
      - audio-playback
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - opengl
    desktop: usr/share/applications/linux-photo-booth.desktop
    environment:
      FLUTTER_ENGINE_RUNTIME_MODE: release
      FLUTTER_ENGINE_SWITCH_TO_IMPELLER: "0"
      GTK_USE_PORTAL: "0"
      GTK_A11Y: "none"
      GDK_BACKEND: "x11,wayland"

  photo-booth-server:
    command: bin/server.py
    plugs:
      - cups-control
      - network
      - network-bind
      - home
    daemon: simple
    restart-condition: always

parts:
  flutter-app:
    plugin: flutter
    source: .
    flutter-target: lib/main.dart
    override-build: |
      # Remove problematic pubspec.lock to avoid platform conflicts
      rm -f pubspec.lock
      
      # Run default flutter build
      snapcraftctl build
    build-packages:
      # Essential build tools (Flutter plugin will handle most of these)
      - libgtk-3-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libv4l-dev
      - libcups2-dev
    stage-packages:
      # Core GTK and graphics libraries
      - libgtk-3-0
      - libgtk-3-common
      - libgdk-pixbuf2.0-0
      - libgdk-pixbuf2.0-common
      - libglib2.0-0
      - libcairo2
      - libcairo-gobject2
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libharfbuzz0b
      - libatk1.0-0
      - libatk-bridge2.0-0
      - libjpeg8
      - libpng16-16
      - libtiff6
      - librsvg2-2
      - librsvg2-common
      
      # GStreamer essentials for camera
      - libgstreamer1.0-0
      - libgstreamer-plugins-base1.0-0
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-libav
      
      # Camera and video support
      - libv4l-0
      - v4l-utils
      
      # Printing support
      - libcups2
      
      # X11 essentials
      - libx11-6
      - libxcursor1
      - libxrandr2
      - libxi6
      - libxinerama1
      - libxext6
      - libxfixes3
      - libxdamage1
      - libxcomposite1
      
      # Wayland support
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1
      - libxkbcommon0
      
      # Additional GTK dependencies
      - adwaita-icon-theme
      - hicolor-icon-theme
      - shared-mime-info

  python-server:
    plugin: python
    source: .
    python-requirements:
      - requirement.txt
    stage-packages:
      - cups
      - cups-client
    override-build: |
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp server.py $SNAPCRAFT_PART_INSTALL/bin/server.py
      chmod +x $SNAPCRAFT_PART_INSTALL/bin/server.py

  desktop-file:
    plugin: dump
    source: snap/local/desktop/
    organize:
      linux-photo-booth.desktop: usr/share/applications/linux-photo-booth.desktop

  launcher:
    plugin: dump
    source: snap/local/
    organize:
      run-booth: bin/run-booth

  config:
    plugin: dump
    source: ubuntu-core/
    organize:
      setup-ubuntu-core.sh: usr/local/bin/setup-ubuntu-core.sh