name: linux-photo-booth
version: '1.0.0'
summary: Professional photo booth application for Ubuntu Core
description: |
  A professional photo booth application designed for Ubuntu Core and Ubuntu Frame.
  Perfect for events, parties, and commercial photo booth installations.
  
  Features:
  - Real-time camera capture using GStreamer
  - Multiple photo layouts (1x1, 2x2)
  - Frame overlay system with customizable templates
  - Direct printing via CUPS
  - Countdown timer with visual feedback
  - Touch-optimized interface
  - Automatic kiosk mode with Ubuntu Frame
  - Background themes and customization
  - Remote management capabilities

grade: stable
confinement: strict
base: core24

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]


apps:
  linux-photo-booth:
    command: bin/run-booth
    extensions: [gnome]
    plugs:
      - camera
      - cups-control
      - network
      - network-bind
      - audio-playback
      - desktop
      - wayland
      - x11
      - opengl
      - raw-usb
    desktop: usr/share/applications/linux-photo-booth.desktop
    environment:
      FLUTTER_ENGINE_RUNTIME_MODE: release
      FLUTTER_ENGINE_SWITCH_TO_IMPELLER: "0"
      GTK_USE_PORTAL: "0"
      GTK_A11Y: "none"
      GDK_BACKEND: "wayland,x11"
      TMPDIR: "$SNAP_USER_COMMON"
      NO_PROXY: "localhost,127.0.0.1"
      MESA_GL_VERSION_OVERRIDE: "3.2"
      MALLOC_TRIM_THRESHOLD_: "100000"

  photo-booth-server:
    command: bin/server.py
    plugs:
      - cups-control
      - network
      - network-bind
    daemon: simple
    restart-condition: always
    restart-delay: 5s

parts:
  flutter-app:
    plugin: flutter
    source: .
    flutter-target: lib/main.dart
    override-build: |
      # Remove problematic pubspec.lock to avoid platform conflicts
      rm -f pubspec.lock
      
      # Run default flutter build
      snapcraftctl build
    build-packages:
      - libgtk-3-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libv4l-dev
      - libcups2-dev
    stage-packages:
      - bash
      - coreutils
      - libgstreamer1.0-0
      - libgstreamer-plugins-base1.0-0
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-libav
      - libv4l-0
      - v4l-utils
      - libcups2
      - dmz-cursor-theme
      - adwaita-icon-theme

  python-server:
    plugin: python
    source: .
    python-requirements:
      - requirements.txt
    stage-packages:
      - cups
      - cups-client
    override-build: |
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp server.py $SNAPCRAFT_PART_INSTALL/bin/server.py
      chmod +x $SNAPCRAFT_PART_INSTALL/bin/server.py

  desktop-file:
    plugin: dump
    source: snap/local/desktop/
    organize:
      linux-photo-booth.desktop: usr/share/applications/linux-photo-booth.desktop

  launcher:
    plugin: dump
    source: snap/local/
    organize:
      run-booth: bin/run-booth

  config:
    plugin: dump
    source: ubuntu-core/
    organize:
      setup-ubuntu-core.sh: usr/local/bin/setup-ubuntu-core.sh