name: linux-photo-booth
version: '1.0.0'
summary: Professional photo booth application for Ubuntu Core
description: |
  A professional photo booth application designed for Ubuntu Core and Ubuntu Frame.
  Perfect for events, parties, and commercial photo booth installations.
  
  Features:
  - Real-time camera capture using GStreamer
  - Multiple photo layouts (1x1, 2x2)
  - Frame overlay system with customizable templates
  - Direct printing via CUPS
  - Countdown timer with visual feedback
  - Touch-optimized interface
  - Automatic kiosk mode with Ubuntu Frame
  - Background themes and customization
  - Remote management capabilities

grade: stable
confinement: strict

base: core22

architectures:
  - build-on: amd64
    run-on: amd64
  - build-on: arm64
    run-on: arm64

apps:
  linux-photo-booth:
    command: bin/run-booth
    plugs:
      - camera
      - cups-control
      - network
      - network-bind
      - home
      - desktop
      - desktop-legacy
      - gsettings
      - wayland
    desktop: linux-photo-booth.desktop

  photo-booth-server:
    command: bin/server.py
    plugs:
      - cups-control
      - network
      - network-bind
      - home
    daemon: simple
    restart-condition: always

parts:
  flutter-sdk:
    plugin: nil
    source: https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.24.5-stable.tar.xz
    source-type: tar
    override-build: |
      snapcraftctl build
      chmod -R +w $SNAPCRAFT_PART_INSTALL

  flutter-app:
    plugin: cmake
    source: .
    after: [flutter-sdk]
    build-packages:
      - build-essential
      - cmake
      - ninja-build
      - pkg-config
      - libgtk-3-dev
      - libx11-dev
      - libxcursor-dev
      - libxrandr-dev
      - libxss-dev
      - libasound2-dev
      - libpulse-dev
      - libdrm-dev
      - libgles2-mesa-dev
      - libegl1-mesa-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-libav
      - gstreamer1.0-tools
      - libv4l-dev
      - v4l-utils
      - libcups2-dev
      - python3-dev
      - python3-pip
      - libwayland-dev
      - libxkbcommon-dev
    stage-packages:
      - libgstreamer1.0-0
      - libgstreamer-plugins-base1.0-0
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-libav
      - gstreamer1.0-tools
      - libv4l-0
      - v4l-utils
      - cups
      - cups-client
      - libcups2
      - python3
      - python3-pip
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1
      - libxkbcommon0
    override-build: |
      export PATH="$SNAPCRAFT_STAGE/flutter/bin:$PATH"
      
      export PUB_CACHE="$SNAPCRAFT_PART_BUILD/.pub-cache"
      
      flutter config --no-analytics
      flutter pub get
      flutter build linux --release
      
      cp -r build/linux/x64/release/bundle/* $SNAPCRAFT_PART_INSTALL/
      
      chmod +x $SNAPCRAFT_PART_INSTALL/linux_photo_booth

  python-server:
    plugin: python
    source: .
    requirements:
      - Flask==3.0.3
      - pycups==2.0.1
    stage-packages:
      - python3
      - python3-pip
      - cups
      - cups-client
      - libcups2
    organize:
      server.py: bin/server.py

  desktop-file:
    plugin: dump
    source: snap/desktop
    organize:
      linux-photo-booth.desktop: usr/share/applications/linux-photo-booth.desktop

  launcher:
    plugin: dump
    source: snap/local
    organize:
      run-booth: bin/run-booth

  # Configuration files for Ubuntu Core
  config:
    plugin: dump
    source: ubuntu-core
    organize:
      setup-ubuntu-core.sh: usr/local/bin/setup-ubuntu-core.sh 